### PR TITLE
Implementations of update, updateLookupWithKey

### PR DESCRIPTION
**Pull request by isturdy**
Mostly routine, I think.

### CODE REVIEW

**Comment by bcdarwin** [comment]
Did you check if defining `updateWithKey` in terms of `updateLookupWithKey` incurs a performance hit? If not, someone should look into it.

**Comment by isturdy** [comment]
A quick check indicates that whatever hit there may be is within the noise of the benchmarks. I had been following Data.Map in not doing so, but their `updateLookupWithKey` is much slower than `Map.update`. bos--if this sounds reasonable to you I can put together a new set of commits tomorrow.

(As a bit of an aside, I thought that the problems in the Map implementation came from their passing the value out in tuples, and wrote a [continuation-based `Map.updateLookupWithKey`](https://github.com/isturdy/containers/blob/continuations/Data/Map/Base.hs#L888) that avoided them. That approach only regained ~10% of the performance difference between `Map.updateWithKey` and the original `Map.updateLookupWithKey` on the containers benchmarks, leaving me somewhat puzzled as to what is causing its performance problems (assuming that I did not bungle the continuations implementation).)

**Comment by bos** [comment]
I think @bcdarwin's suggestion is a good one, so I'll keep this open and wait for @isturdy to replace it with a rebased commit that reduces the duplication. Thanks, folks!

**Comment by isturdy** [comment]
That I think does it.

**Comment by bcdarwin** [comment]
It looks like you've accidentally erased `t_mapMaybeWithKey`. Also, a couple (possibly nitpicking) issues: the benchmark for `updateLookupWithKey` doesn't seem to evaluate the first part of the tuple (though, looking at the code, this doesn't really matter); and there's some bloat in the test code between `update`, `updateWithKey`, and `updateLookupWithKey` (but maybe the alternative is confusing to read?).

**Comment by isturdy** [comment]
Thanks for catching `t_mapMaybeWithKey`; it got clobbered in a rebase gone wrong.I am not much worried about the `updateLookupWithKey` benchmark; the original problem I found is that the map implementation returns a tuple that is lazy in both values, doing almost no work unless you force one of the values. The present benchmark does not force evaluation of the new value (in either datastructure), but does force the tree update which is the difference I seek to measure (and parallels the laziness properties of the benchmarks in `containers`).

**Comment by isturdy** [comment]
Bah. I seem to have gotten my git branches really messed up, and this now points to and old set of commits. Let me start this over.

**Pull request closed without merging**
